//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachBoy.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем HelloWorldResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TeachBoy.ServiceReference1.HelloWorldResponse HelloWorld(TeachBoy.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TeachBoy.ServiceReference1.HelloWorldResponse> HelloWorldAsync(TeachBoy.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем MaxTwoResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MaxTwo", ReplyAction="*")]
        TeachBoy.ServiceReference1.MaxTwoResponse MaxTwo(TeachBoy.ServiceReference1.MaxTwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MaxTwo", ReplyAction="*")]
        System.Threading.Tasks.Task<TeachBoy.ServiceReference1.MaxTwoResponse> MaxTwoAsync(TeachBoy.ServiceReference1.MaxTwoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TeachBoy.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TeachBoy.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeachBoy.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TeachBoy.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaxTwoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MaxTwo", Namespace="http://tempuri.org/", Order=0)]
        public TeachBoy.ServiceReference1.MaxTwoRequestBody Body;
        
        public MaxTwoRequest() {
        }
        
        public MaxTwoRequest(TeachBoy.ServiceReference1.MaxTwoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MaxTwoRequestBody {
        
        public MaxTwoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MaxTwoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MaxTwoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TeachBoy.ServiceReference1.MaxTwoResponseBody Body;
        
        public MaxTwoResponse() {
        }
        
        public MaxTwoResponse(TeachBoy.ServiceReference1.MaxTwoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MaxTwoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MaxTwoResult;
        
        public MaxTwoResponseBody() {
        }
        
        public MaxTwoResponseBody(string MaxTwoResult) {
            this.MaxTwoResult = MaxTwoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TeachBoy.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TeachBoy.ServiceReference1.WebService1Soap>, TeachBoy.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeachBoy.ServiceReference1.HelloWorldResponse TeachBoy.ServiceReference1.WebService1Soap.HelloWorld(TeachBoy.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TeachBoy.ServiceReference1.HelloWorldRequest inValue = new TeachBoy.ServiceReference1.HelloWorldRequest();
            inValue.Body = new TeachBoy.ServiceReference1.HelloWorldRequestBody();
            TeachBoy.ServiceReference1.HelloWorldResponse retVal = ((TeachBoy.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeachBoy.ServiceReference1.HelloWorldResponse> TeachBoy.ServiceReference1.WebService1Soap.HelloWorldAsync(TeachBoy.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeachBoy.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            TeachBoy.ServiceReference1.HelloWorldRequest inValue = new TeachBoy.ServiceReference1.HelloWorldRequest();
            inValue.Body = new TeachBoy.ServiceReference1.HelloWorldRequestBody();
            return ((TeachBoy.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TeachBoy.ServiceReference1.MaxTwoResponse TeachBoy.ServiceReference1.WebService1Soap.MaxTwo(TeachBoy.ServiceReference1.MaxTwoRequest request) {
            return base.Channel.MaxTwo(request);
        }
        
        public string MaxTwo() {
            TeachBoy.ServiceReference1.MaxTwoRequest inValue = new TeachBoy.ServiceReference1.MaxTwoRequest();
            inValue.Body = new TeachBoy.ServiceReference1.MaxTwoRequestBody();
            TeachBoy.ServiceReference1.MaxTwoResponse retVal = ((TeachBoy.ServiceReference1.WebService1Soap)(this)).MaxTwo(inValue);
            return retVal.Body.MaxTwoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TeachBoy.ServiceReference1.MaxTwoResponse> TeachBoy.ServiceReference1.WebService1Soap.MaxTwoAsync(TeachBoy.ServiceReference1.MaxTwoRequest request) {
            return base.Channel.MaxTwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeachBoy.ServiceReference1.MaxTwoResponse> MaxTwoAsync() {
            TeachBoy.ServiceReference1.MaxTwoRequest inValue = new TeachBoy.ServiceReference1.MaxTwoRequest();
            inValue.Body = new TeachBoy.ServiceReference1.MaxTwoRequestBody();
            return ((TeachBoy.ServiceReference1.WebService1Soap)(this)).MaxTwoAsync(inValue);
        }
    }
}
